from typing import Protocol, Any


class PipelineHook(Protocol):
    def on_before(self, context: Any) -> None: ...
    def on_after(self, context: Any, result: Any) -> None: ...
    def on_error(self, context: Any, error: Exception) -> None: ...
