from pydantic import Field
from ..base import ValueObject
from .cost import CostRecord


class TokenUsage(ValueObject):
    """
    Konsumsi token LLM dalam satu eksekusi.
    """

    prompt_tokens: int = Field(default=0, description="Tokens used for input prompt")
    completion_tokens: int = Field(default=0, description="Tokens generated by model")
    total_tokens: int = Field(default=0, description="Total tokens consumed")
    estimated_cost: CostRecord | None = Field(default=None, description="Estimated financial cost")
