CREATE DATABASE aetheros_test;

GRANT ALL PRIVILEGES ON DATABASE aetheros TO aetheros;
GRANT ALL PRIVILEGES ON DATABASE aetheros_test TO aetheros;

\c aetheros
CREATE SCHEMA IF NOT EXISTS aetheros;
CREATE SCHEMA IF NOT EXISTS workspace;
CREATE SCHEMA IF NOT EXISTS storage;
CREATE SCHEMA IF NOT EXISTS repository;
CREATE SCHEMA IF NOT EXISTS artifact;
CREATE SCHEMA IF NOT EXISTS organization;

GRANT ALL PRIVILEGES ON SCHEMA aetheros TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA workspace TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA storage TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA repository TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA artifact TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA organization TO aetheros;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

\c aetheros_test
CREATE SCHEMA IF NOT EXISTS aetheros;
CREATE SCHEMA IF NOT EXISTS workspace;
CREATE SCHEMA IF NOT EXISTS storage;
CREATE SCHEMA IF NOT EXISTS repository;
CREATE SCHEMA IF NOT EXISTS artifact;
CREATE SCHEMA IF NOT EXISTS organization;

GRANT ALL PRIVILEGES ON SCHEMA aetheros TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA workspace TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA storage TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA repository TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA artifact TO aetheros;
GRANT ALL PRIVILEGES ON SCHEMA organization TO aetheros;