from typing import Protocol, Any, List, Dict


class RegistryProtocol(Protocol):
    def register(self, key: str, instance: Any) -> None: ...
    def unregister(self, key: str) -> None: ...
    def find(self, key: str) -> Any | None: ...
    def filter(self, predicate: callable) -> List[Any]: ...
    def search(self, query: str) -> List[Any]: ...
    def replace(self, key: str, new_instance: Any) -> None: ...
    def snapshot(self) -> Dict[str, Any]: ...
    def export(self) -> str: ...
    def import_data(self, data: str) -> None: ...
